name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t thisisiliya/httpr:latest .

      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag the Docker image
        run: docker tag thisisiliya/httpr:latest docker.pkg.github.com/thisisiliya/httpr/httpr:latest
      
      - name: Push the Docker image to GitHub Packages
        run: docker push docker.pkg.github.com/thisisiliya/httpr/httpr:latest
      
      - name: Push the Docker image to Docker Hub
        run: docker push thisisiliya/httpr:latest
